// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLHbkMPgPQtewsoZ6yzB3wtr0m4OdTwk8',
    appId: '1:944514748908:web:dbeafd3339f26c7579f0c9',
    messagingSenderId: '944514748908',
    projectId: 'device-streaming-e3f5f0d7',
    authDomain: 'device-streaming-e3f5f0d7.firebaseapp.com',
    storageBucket: 'device-streaming-e3f5f0d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-M4y5-7-M0X8D7y5wnWK18X5Nd03cMfA',
    appId: '1:944514748908:android:a7c6c0305a7eb27f79f0c9',
    messagingSenderId: '944514748908',
    projectId: 'device-streaming-e3f5f0d7',
    storageBucket: 'device-streaming-e3f5f0d7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxhxl59665EfiAhFAVpEU7zUboRiuYUY',
    appId: '1:944514748908:ios:009ec8fe1539135379f0c9',
    messagingSenderId: '944514748908',
    projectId: 'device-streaming-e3f5f0d7',
    storageBucket: 'device-streaming-e3f5f0d7.firebasestorage.app',
    iosBundleId: 'com.example.mealPlan',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxhxl59665EfiAhFAVpEU7zUboRiuYUY',
    appId: '1:944514748908:ios:009ec8fe1539135379f0c9',
    messagingSenderId: '944514748908',
    projectId: 'device-streaming-e3f5f0d7',
    storageBucket: 'device-streaming-e3f5f0d7.firebasestorage.app',
    iosBundleId: 'com.example.mealPlan',
  );

}